# Generated by Django 3.0.6 on 2020-05-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvShowsApp', '0002_show_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='releaseDate',
            field=models.DateField(),
        ),
    ]
