# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0786ee571d3ed264703fd2490307d409900f6c3fa7746ea5255f30378db752e461ae27af0384c1ba64e7136bddc299c780dd45724893c13fe90a2cd9756fbb7e

test:
  secret_key_base: 8cae7e2af07e075e59d80c53bab75653c39c3812f821e1dbebb566e99dc97c5f13d7241300260065ac18cc3af5c8118309027ba6fc55b8cd4e62ef2e0966a8b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
