# Generated by Django 3.0.6 on 2020-05-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthorsApp', '0002_auto_20200516_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Notes Go Here'),
        ),
    ]
