# Generated by Django 3.0.6 on 2020-05-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadonApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='products', to='amadonApp.Product'),
        ),
    ]
