# Generated by Django 3.0.6 on 2020-05-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amadonApp', '0002_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
