# Generated by Django 3.0.6 on 2020-05-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amadonApp', '0004_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
    ]
