# Generated by Django 3.0.6 on 2020-05-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltExamApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='userPost',
            new_name='userWhoPosted',
        ),
    ]
