# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4e3c99aac3e9a17bf9e6418ca350d616a6b7c74b43a038cba8815d09149b98fd1590b551d71f7b0939c7cab1dd4a6cac31c7390e4839b33d501aae6aa0bcb52

test:
  secret_key_base: 4791af0e2fde4075ac4ab3df188140478121ef835fac27e80163a2b60f6c240c6c1af62f63b5c605d749b2f183704ddf00dce3048c6ddd7d9a1d6130decbab7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
